### PR TITLE
Fix duration of pipeline jobs

### LINKED ISSUE #51: Support for Jenkins2 Pipeline
In Jenkins2 Pipeline, Datadog Event Monitor is unstable work.
Maybe cause, in Jenkins2 Pipeline, [run.getDuration()](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L211) is always return 0.

### PR DESCRIPTION
**Pull request by ulich**
Fixes #51.

I took over the work from https://github.com/DataDog/jenkins-datadog-plugin/pull/53 and added the proposed fallback

Btw: The code is really hard to test. I did not want to do a full refactoring to make it testable, that's why I used powermock...

### CODE REVIEW

**Comment by irabinovitch** [comment]
Thanks @ulich . We appreciate your contribution here. We will be reviewing this PR shortly and get back to you with feedback.

**Comment by Geethree** [comment]
Any chance you'll be reviewing this soon?

**Comment by sjenriquez** [comment]
@ulich Sorry for the long delay here! I am preparing a new release the should go out next week.

The test is failing on a `java.lang.NullPointerException` for me, are there some missing requirements in the test?

**Comment by ulich** [comment]
Sorry, tests are fixed now. When I merged the master I pulled some changes in that caused the tests to fail, but I did not re-run them...

Maybe you could set up automated running of tests for PRs

**Comment by sjenriquez** [comment]
Thanks @ulich! This will go out shortly with our next release.

**Pull request merged**
